/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-02-23 02:14:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class woof_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/css; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-color: #ffeee5\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("\tfont-family: \"Palatino Linotype\", \"Book Antiqua\", Palatino, serif\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigation\r\n");
      out.write("{\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("\tpadding-top: 10px;\r\n");
      out.write("\tpadding-bottom: 10px;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("\tbackground-color: #e4b48f;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigation ul\r\n");
      out.write("{\r\n");
      out.write("\tlist-style:none;\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin:0;\r\n");
      out.write("\tpadding:0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigation ul a\r\n");
      out.write("{\r\n");
      out.write("\tdisplay:block;\r\n");
      out.write("\tcolor:black;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\tfont-weight:700;\r\n");
      out.write("\tfont-size:18px;\r\n");
      out.write("\tline-height:32px;\r\n");
      out.write("\tpadding:0 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigation ul li\r\n");
      out.write("{\r\n");
      out.write("\tposition:relative;\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-right: 10px;\r\n");
      out.write("\tpadding:0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".current-menu-item\r\n");
      out.write("{\r\n");
      out.write("\tbackground: #ffeee5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#navigation ul li:hover\r\n");
      out.write("{\r\n");
      out.write("\tbackground:#ffeee5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\ttop: 50%;\r\n");
      out.write("\tleft: 50%;\r\n");
      out.write("\t-ms-transform: translate(-50%, -50%);\r\n");
      out.write("\ttransform: translate(-50%, -50%);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\theight: relative;\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tborder: 3px solid black;\r\n");
      out.write("\tborder-radius: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buttonOne {\r\n");
      out.write("\tbackground-color: #e4b48f;\r\n");
      out.write("\tborder: none;\r\n");
      out.write("\tpadding: 15px 32px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("\tfont-size: 16px;\r\n");
      out.write("\tfont-family: \"Palatino Linotype\", \"Book Antiqua\", Palatino, serif;\r\n");
      out.write("\tborder-radius: 12px;\r\n");
      out.write("\ttransition-duration: 0.4s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".buttonOne:hover {\r\n");
      out.write("  background-color: #e4b48f;\r\n");
      out.write("  color: #ffeee5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer {\r\n");
      out.write("  position: fixed;\r\n");
      out.write("  left: 0;\r\n");
      out.write("  bottom: 0;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  background-color: #e4b48f;\r\n");
      out.write("  color: #ffeee5;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
